#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Greg.Xrm.Mcp.FormEngineer.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public partial class DataverseContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public DataverseContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Greg.Xrm.Mcp.FormEngineer.Model.AppModule"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Greg.Xrm.Mcp.FormEngineer.Model.AppModule> AppModuleSet
		{
			get
			{
				return this.CreateQuery<Greg.Xrm.Mcp.FormEngineer.Model.AppModule>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Greg.Xrm.Mcp.FormEngineer.Model.AppModuleComponent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Greg.Xrm.Mcp.FormEngineer.Model.AppModuleComponent> AppModuleComponentSet
		{
			get
			{
				return this.CreateQuery<Greg.Xrm.Mcp.FormEngineer.Model.AppModuleComponent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Greg.Xrm.Mcp.FormEngineer.Model.AppModuleRoles"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Greg.Xrm.Mcp.FormEngineer.Model.AppModuleRoles> AppModuleRolesSet
		{
			get
			{
				return this.CreateQuery<Greg.Xrm.Mcp.FormEngineer.Model.AppModuleRoles>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Greg.Xrm.Mcp.FormEngineer.Model.SavedQuery"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Greg.Xrm.Mcp.FormEngineer.Model.SavedQuery> SavedQuerySet
		{
			get
			{
				return this.CreateQuery<Greg.Xrm.Mcp.FormEngineer.Model.SavedQuery>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Greg.Xrm.Mcp.FormEngineer.Model.SiteMap"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Greg.Xrm.Mcp.FormEngineer.Model.SiteMap> SiteMapSet
		{
			get
			{
				return this.CreateQuery<Greg.Xrm.Mcp.FormEngineer.Model.SiteMap>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Greg.Xrm.Mcp.FormEngineer.Model.SystemForm"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Greg.Xrm.Mcp.FormEngineer.Model.SystemForm> SystemFormSet
		{
			get
			{
				return this.CreateQuery<Greg.Xrm.Mcp.FormEngineer.Model.SystemForm>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Greg.Xrm.Mcp.FormEngineer.Model.UserQuery"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Greg.Xrm.Mcp.FormEngineer.Model.UserQuery> UserQuerySet
		{
			get
			{
				return this.CreateQuery<Greg.Xrm.Mcp.FormEngineer.Model.UserQuery>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Greg.Xrm.Mcp.FormEngineer.Model.WebResource"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Greg.Xrm.Mcp.FormEngineer.Model.WebResource> WebResourceSet
		{
			get
			{
				return this.CreateQuery<Greg.Xrm.Mcp.FormEngineer.Model.WebResource>();
			}
		}

		/// <summary>
		/// Gets a binding to the set of all <see cref="Greg.Xrm.Mcp.FormEngineer.Model.SavedQueryVisualization"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Greg.Xrm.Mcp.FormEngineer.Model.SavedQueryVisualization> SavedQueryVisualizationSet
		{
			get
			{
				return this.CreateQuery<Greg.Xrm.Mcp.FormEngineer.Model.SavedQueryVisualization>();
			}
		}
	}
}
#pragma warning restore CS1591
